XXX PoC template v0.6

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -1,67 +1,75 @@
+---
 stages:
-- name: Build Stage
+- name: Build Project
   inputs:
-  - type: git
+  - url: https://github.com/XXX-DEV1/DevOps_PoC_1_XXX.git
+    type: git
     branch: master
-    service: ${REPO}
+    dir_name: null
   jobs:
-  - name: Build
+  - name: Build Project
     type: builder
-    artifact_dir: ''
+    artifact_dir: target
     build_type: maven
     script: |-
       #!/bin/bash
+      export JAVA_HOME=$JAVA8_HOME
       mvn -B package
-- name: Test Stage
-  inputs:
-  - type: job
-    stage: Build Stage
-    job: Build
-    dir_name: null
-  jobs:
-  - name: Test
-    type: tester
-    script: |-
-      #!/bin/bash
-      mvn test
+      cp Dockerfile $ARCHIVE_DIR/
+      cp manifest.yml $ARCHIVE_DIR/
     enable_tests: true
     test_file_pattern: target/surefire-reports/TEST-*.xml
-- name: Deploy Stage
+- name: Deploy Web App
   inputs:
   - type: job
-    stage: Build Stage
-    job: Build
+    stage: Build Project
+    job: Build Project
     dir_name: null
   properties:
+  - name: TARGET
+    value: spring-petclinic-1.4.2.war
+    type: text
   - name: SERVERS
-    value: 10.0.0.1
+    value: SERVER_LIST_HERE_BY_LINE
     type: text_area
   - name: SSH_KEY
-    value: KEY
+    value: PRIVATE_KEY_HERE
     type: text_area
   - name: REMOTE_COMMAND
     value: |-
-      /opt/cops/apache-tomcat-8.5.5/bin/shutdown.sh
-      rm -rf /opt/cops/apache-tomcat-8.5.5/webapps/sample-project
-      mv /tmp/sample-project.war /opt/cops/apache-tomcat-8.5.5/webapps/
-      mv -f /tmp/sample-project.war /opt/cops/apache-tomcat-8.5.5/webapps/
-      /opt/cops/apache-tomcat-8.5.5/bin/startup.sh
+      /opt/apache-tomcat-8.5.11/bin/shutdown.sh
+
+      rm -rf /opt/petclinic/webapp
+      unzip -q /tmp/spring-petclinic-1.4.2.war -d /opt/petclinic/webapp
+
+      /opt/apache-tomcat-8.5.11/bin/startup.sh
     type: text_area
-  - name: CONSUL_HOST
-    value: 169.44.13.129
-    type: text
-  - name: CONSUL_TARGET
-    value: sample.service.dc1.consul
-    type: text
-  - name: CONSUL_PORT
-    value: '8600'
-    type: text
-  - name: CONSUL_SERVICE
-    value: sample
-    type: text
-  - name: CONSUL_API
-    value: http://169.44.13.129:8500/v1
-    type: text
+  jobs:
+  - name: Deploy
+    type: tester
+    script: |-
+      #!/bin/bash
+      SSH_KEY_FILE="$(mktemp)"
+      SSH_OPTIONS="-o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_KEY_FILE"
+      SSH_USER="root"
+
+      echo "$SSH_KEY" > "$SSH_KEY_FILE"
+
+      for SERVER in ${SERVERS};
+      do
+          echo "server: $SERVER"
+          scp $SSH_OPTIONS $TARGET $SSH_USER@$SERVER:/tmp/
+          echo "eval $REMOTE_COMMAND" | ssh $SSH_OPTIONS $SSH_USER@$SERVER 2>/dev/null
+          echo $?
+      done
+
+      rm "$SSH_KEY_FILE"
+- name: Deploy to Cloud Foundry
+  inputs:
+  - type: job
+    stage: Build Project
+    job: Build Project
+    dir_name: null
   jobs:
   - name: Deploy
     type: deployer
@@ -70,41 +78,134 @@ stages:
       organization: ${CF_ORGANIZATION}
       space: ${CF_SPACE}
       application: ${CF_APP}
-
     script: |
       #!/bin/bash
-      SSH_KEY_FILE="$(mktemp)"
-      SSH_OPTIONS="-o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_KEY_FILE"
-      SSH_USER="root"
-
-      #echo "$SSH_KEY" > "$SSH_KEY_FILE"
-      curl $CONSUL_API/kv/${CONSUL_SERVICE}_key |grep Value |cut -d '"' -f 4 |base64 --decode > "$SSH_KEY_FILE"
-      cat $SSH_KEY_FILE
-      #SERVERS=$(dig $CONSUL_HOST -p $CONSUL_PORT $CONSUL_TARGET +short)
-      #SERVERS=$(nslookup $CONSUL_TARGET $CONSUL_HOST -port=$CONSUL_PORT |tail -n +4 |grep Address |cut -d " " -f 2)
-      cat > get_target.py << __EOF__
-      import json
-      import urllib2
-
-      URL = "$CONSUL_CATALOG/catalog/service/$CONSUL_SERVICE"
-
-      res = urllib2.urlopen(URL)
-      data = json.load(res)
-      print ' '.join(map(lambda x: x['Address'], data))
-      __EOF__
-      SERVERS=$(python get_target.py)
-
-      echo "Deploying to: ${SERVERS}"
-
-      for SERVER in ${SERVERS};
-      do
-          echo "server: $SERVER"
-          scp $SSH_OPTIONS ./target/sample-project.war $SSH_USER@$SERVER:/tmp/
-          echo "eval $REMOTE_COMMAND" | ssh $SSH_OPTIONS $SSH_USER@$SERVER 2>/dev/null
-          echo $?
-      done
-
-      rm "$SSH_KEY_FILE"
+      # uncomment the next line for unsuccessful deployment (PagerDuty testing)
+      #sed -i 's/256M/99999M/g' manifest.yml
+      sed -i 's/256M/512M/g' manifest.yml
+      cf push "${CF_APP}"
+- name: Build Container Image
+  inputs:
+  - type: job
+    stage: Build Project
+    job: Build Project
+    dir_name: null
+  jobs:
+  - name: Build
+    type: builder
+    extension_id: ibm.devops.services.pipeline.container.builder
+    target:
+      region_id: ${CF_REGION_ID}
+      organization: ${CF_ORGANIZATION}
+      space: ${CF_SPACE}
+    COMMAND: "#!/bin/bash\n# The following colors have been defined to help with presentation\
+      \ of logs: green, red, label_color, no_color.  \nlog_and_echo \"$LABEL\" \"\
+      Starting build script\"\n\n# The IBM Container BM Containers plug-in (cf ic),\
+      \ Git client (git), and IDS Inventory CLI (ids-inv) have been installed.\n#\
+      \ Based on the organization and space selected in the Job credentials are in\
+      \ place for both IBM Container Service and IBM Bluemix \n#####################\n\
+      # Run unit tests    #\n#####################\nlog_and_echo \"$LABEL\" \"No unit\
+      \ tests cases have been checked in\"\n\n######################################\n\
+      # Build Container via Dockerfile     #\n######################################\n\
+      \n# REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}\n# FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}\n\
+      # If you wish to receive slack notifications, set SLACK_WEBHOOK_PATH as a property\
+      \ on the stage.\n\nif [ -f Dockerfile ]; then \n    log_and_echo \"$LABEL\"\
+      \ \"Building ${FULL_REPOSITORY_NAME}\"\n    ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l info -m \"New container build requested for ${FULL_REPOSITORY_NAME}\"\n\
+      \    # build image\n    BUILD_COMMAND=\"\"\n    if [ \"${USE_CACHED_LAYERS}\"\
+      \ == \"true\" ]; then \n        BUILD_COMMAND=\"build --pull --tag ${FULL_REPOSITORY_NAME}\
+      \ ${WORKSPACE}\"\n        ice_retry ${BUILD_COMMAND}\n        RESULT=$?\n  \
+      \  else \n        BUILD_COMMAND=\"build --no-cache --tag ${FULL_REPOSITORY_NAME}\
+      \ ${WORKSPACE}\"\n        ice_retry ${BUILD_COMMAND}\n        RESULT=$?\n  \
+      \  fi \n\n    if [ $RESULT -ne 0 ]; then\n        log_and_echo \"$ERROR\" \"\
+      Error building image\"\n        ice_retry info \n        ice_retry images\n\
+      \        ${EXT_DIR}/print_help.sh\n        ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l bad -m \"Container build of ${FULL_REPOSITORY_NAME} failed. $(get_error_info)\"\
+      \n        exit 1\n    else\n        log_and_echo \"$SUCCESSFUL\" \"Container\
+      \ build of ${FULL_REPOSITORY_NAME} was successful\"\n        ${EXT_DIR}/utilities/sendMessage.sh\
+      \ -l good -m \"Container build of ${FULL_REPOSITORY_NAME} was successful\"\n\
+      \    fi  \nelse \n    log_and_echo \"$ERROR\" \"Dockerfile not found in project\"\
+      \n    ${EXT_DIR}/utilities/sendMessage.sh -l bad -m \"Failed to get Dockerfile.\
+      \ $(get_error_info)\"\n    exit 1\nfi  \n\n######################################################################################\n\
+      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE\
+      \    #\n######################################################################################\n\
+      echo \"IMAGE_NAME=${FULL_REPOSITORY_NAME}\" >> $ARCHIVE_DIR/build.properties"
+    IMAGE_NAME: devops_poc_1_xxx
+    USE_CACHED_LAYERS: 'true'
+- name: Deploy to IBM Containers
+  inputs:
+  - type: job
+    stage: Build Container Image
+    job: Build
+    dir_name: null
+  triggers:
+  - type: stage
+  jobs:
+  - name: Deploy
+    type: deployer
+    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
+    target:
+      region_id: ${CF_REGION_ID}
+      organization: ${CF_ORGANIZATION}
+      space: ${CF_SPACE}
+    COMMAND: "#!/bin/bash\n# The following are some example deployment scripts.  Use\
+      \ these as is or fork them and include your updates here:\necho -e \"${label_color}Starting\
+      \ deployment script${no_color}\"\n\n\n# To view/fork this script goto: https://github.com/Osthanes/deployscripts\n\
+      # git_retry will retry git calls to prevent pipeline failure on temporary github\
+      \ problems\n# the code can be found in git_util.sh at https://github.com/Osthanes/container_deployer\n\
+      git_retry clone https://github.com/Osthanes/deployscripts.git deployscripts\n\
+      \n\n# You can deploy your Image as either a single Container or as a Container\
+      \ \n# Group.  A Container Group deploys a number of containers to enhance\n\
+      # scalability or reliability.  By default we will deploy as a single \n# container.\
+      \  To switch to a group deploy, comment out the line below\n# containing deploycontainer.sh\
+      \ and uncomment the line for deploygroup.sh\n\n# Deploy with containers:\n#\
+      \ Optional environment properties (can be set directly in this script, or defined\
+      \ as environment properties):\n#      NAME              Value         Description\n\
+      #   =============      =========     ==============\n#   BIND_TO           \
+      \  String       Specify a Bluemix application name that whose bound services\
+      \ you wish to make available to the container.  By default this is not set.\n\
+      #   CONTAINER_SIZE      String       Specify container size: pico (64), nano\
+      \ (128), micro (256), tiny (512), small (1024), medium (2048),\n#          \
+      \                                                  large (4096), x-large (8192),\
+      \ 2x-large (16384).\n#                                    Default is micro (256).\n\
+      #   CONCURRENT_VERSIONS Number       Number of versions of this container to\
+      \ leave active.  \n#                                    Default is 1\n#\n#/bin/bash\
+      \ deployscripts/deploycontainer.sh\n\n# Deploy Container Group:\n# Optional\
+      \ environment properties (can be set directly in this script, or defined as\
+      \ environment properties):\n#      NAME              Value         Description\n\
+      #   =============      =========     ==============\n#   ROUTE_HOSTNAME    \
+      \  String       Specify the Hostname for the Cloud Foundry Route you wish to\
+      \ assign to this container group.  By default this is not set.\n#   ROUTE_DOMAIN\
+      \        String       Specify domain name for the Cloud Foundry Route you wish\
+      \ to assign to this container group.  By default this is not set.\n#   BIND_TO\
+      \             String       Specify a Bluemix application name that whose bound\
+      \ services you wish to make available to the container.  By default this is\
+      \ not set.\n#   DESIRED_INSTANCES:  Number       Specify the number of instances\
+      \ in the group.  Default value is 1.\n#   AUTO_RECOVERY:      Boolean      Set\
+      \ auto-recovery to true/false.  Default value is false.\n\n#               \
+      \                     Default is false.\n#   CONTAINER_SIZE      String    \
+      \   Specify container size: pico (64), nano (128), micro (256), tiny (512),\
+      \ small (1024), medium (2048),\n#                                          \
+      \                  large (4096), x-large (8192), 2x-large (16384).\n#      \
+      \                              Default is micro (256).\n#   CONCURRENT_VERSIONS\
+      \ Number       Number of versions of this group to leave active.\n#        \
+      \                            Default is 1\n# IF YOU WANT CONTAINER GROUPS ..\
+      \ uncomment the next line, and comment out the previous deployment line (/bin/bash\
+      \ deployscripts/deploygroup.sh)\nexport DESIRED_INSTANCES=2\nexport ROUTE_HOSTNAME=DevOps-PoC-1-XXX-IC\n\
+      /bin/bash deployscripts/deploygroup.sh\n\nRESULT=$?\n\n# source the deploy property\
+      \ file\nif [ -f \"${DEPLOY_PROPERTY_FILE}\" ]; then\n  source \"$DEPLOY_PROPERTY_FILE\"\
+      \nfi\n\n#########################\n# Environment DETAILS   #\n#########################\n\
+      # The environment has been setup.\n# The Cloud Foundry CLI (cf), IBM Container\
+      \ Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python\
+      \ 2.7.3 (python) have been installed.\n# Based on the organization and space\
+      \ selected in the Job credentials are in place for both IBM Container Service\
+      \ and IBM Bluemix\n\n# The following colors have been defined to help with presentation\
+      \ of logs: green, red, label_color, no_color.\nif [ $RESULT -ne 0 ]; then\n\
+      \    echo -e \"${red}Executed failed or had warnings ${no_color}\"\n    ${EXT_DIR}/print_help.sh\n\
+      \    exit $RESULT\nfi\necho -e \"${green}Execution complete${no_label}\""
+    PORT: '80'
+    CONTAINER_NAME: DevOps_PoC_1_XXX
+    DEPLOY_TYPE: red_black
 hooks:
 - enabled: true
   label: null
